### ISSUE TITLE
+4294967295 에서 오류 발생

### ISSUE THREAD

**Issue by witcher42** [batboy118/42_factorization#1]
안녕하세요.
+를 예외처리를 안하셔서(정답이 아니라고 할 수는 없지만)
자리수로 에러를 출력하는 경우 +4294967295 에서 오류가 발생합니다. 
이부분만 제외한다면 정말 멋진 코드였습니다.
함수에 대한 주석도 달아주셔서 이해하기가 정말 편했습니다.
  
![스크린샷(182)](https://user-images.githubusercontent.com/59954400/78451493-e53d0000-76c0-11ea-8845-ab7fafd00b4b.png)

**Comment by AimingBro** [comment]
감사합니다. 조건을 하나 빼먹었네요ㅜㅜ
아래 같이 수정해야 겠습니다!
감사합니다.
```
		if((str[0] != '+' && i > 10) || (str[0] == '+' && i > 11))
			return (-2);
```
