### ISSUE TITLE
코드리뷰(eunhkim)

### ISSUE THREAD

**Issue by eunhyulkim** [batboy118/42_factorization#2]
안녕하세요. 수고 많으셨습니다! 직접 코드를 클론해서 테스트해보았고, 아래와 같이 리뷰 남깁니다.

## 에러
1. 해당 프로그램은 '+' sign을 처리하고 있는데 + sign 사용시 특정 숫자 이상의 입력을 처리하지 못합니다. 
```
./factorization +2294967290
숫자의 범위를 확인 하세요.(2 ~ 4,294,967,295)
```
확인 결과 아래의 코드에 이슈가 있습니다. (앞 분이 남겨주신 이슈에서 에러 및 수정 방안이 기록되었는데, 제가 이 이슈를 쓰고 나서 뒤늦게 확인했습니다. 이왕 썼으니 남겨놓겠습니다.)
```
if(i > 10 || (str[0] == '+' && i > 11))
    return (-2);
```

## 개선사항
1. 에러메시지에 띄어쓰기 오타가 있습니다.
```
숫자의 범위를 확인 하세요. -> 확인하세요.
```
2. 사용되지 않는 함수의 프로토타입이 선안되어 있습니다.
```
unsigned int			ft_atoi_check(char *str);
```
3. 심심풀이 테스트라 크게 중요하지는 않겠지만, 25줄이 넘는 함수, 한글 주석, printf 사용 등이 포함되어 있어서 42 code style로 작성되었다면 더 좋았겠다고 생각했습니다. 함수 개수, 변수명 Align, 함수, 변수 초기화 방식 등 42 style을 따르려고 노력하신 부분들이 많이 보였기에 더 그렇게 느낀 것 같아요.

## 배운 점 & 좋았던 점
함수도 많이 사용하지 않으셨고, 속도도 빨랐습니다. 가독성을 신경 쓰신 흔적도 많이 보였고요. test.md 파일도 코드의 '개선 과정'이 이미지와 함께 잘 정리되어 있어서, '과정을 담으라'는 요구에 정말 부합되는 test.md 파일이라고 느꼈고, 덕분에 저에게서도 학습이 일어났습니다.

다시 한 번 정말 수고 많으셨습니다!

**Comment by AimingBro** [comment]
감사합니다! 충분히 테스트 하지 못한거 같네요 ㅜㅜ
